### ISSUE TITLE
Hang on init-platform with 4.0.0.1349

### ISSUE THREAD

**Issue by kenorb** [FX31337/MQL-Compile-Action#37]
When run compilation with MT 4.0.0.1349, the action hangs forever. It worked with default/previous version.

```
      - name: Compile
        uses: fx31337/mql-compile-action@master
        with:
          init-platform: true
          mt-version: 4.0.0.1349
          verbose: true
```
