### ISSUE TITLE
mt-version: 4.0.0.1359 fails with Error: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by kenorb** [FX31337/MQL-Compile-Action#51]
```
      - name: Compile (build 1359)
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 4.0.0.1359
          path: somefile.mq4
          verbose: true
```

```
Downloading "https://github.com/EA31337/MT-Platforms/releases/download/4.0.0.1359/mt-4.0.0.1359.zip" into "metaeditor4_d11a0c0c5d209b0ddcda2ddc216644.zip"...
Unzipping "metaeditor4_d11a0c0c5d209b0ddcda142ddc216644.zip"...
Renaming MetaTrader's folder from "../unpacked/d11a0c0c5d209b0ddcda142ddc216644/MetaTrader 4" into "../MetaTrader_d11a0c0c5d209b0ddcda142ddc216644"...
Cannot rename MetaTrader's folder!
Error: Error: ENOENT: no such file or directory, lstat '../unpacked/d11a0c0c5d209b0ddcda142ddc2644/MetaTrader 4'
```
